import { useEffect, useMemo, useState } from "react";
import { inventoryApi, inventoryMaterialApi, InventoryApiError, type InventoryDailyRun, type InventoryExport, type InventoryReview, type InventoryMaterial, type InventoryMaterialCandidate } from "./api";
import { InventoryDailySheetSettings } from "./InventoryDailySheetSettings";

export type InventoryPage = "dashboard"|"inbox"|"review"|"materials"|"daily"|"reports"|"settings";
type Page = InventoryPage;
const links:Array<[Page,string,string]>=[["daily","H\u1eb1ng ng\u00e0y","/inventory/daily"],["review","Xem x\u00e9t","/inventory/review"],["materials","V\u1eadt t\u01b0","/inventory/materials"],["settings","C\u1ea5u h\u00ecnh","/inventory/settings"]];
function pageForPath(path:string):Page { const part=path.split("/")[2]||""; return part==="inbox"||part==="review"||part==="materials"||part==="daily"||part==="reports"||part==="settings"?part:"dashboard"; }
function Unavailable({title,detail}:{title:string;detail:string}){return <section className="inventory-empty"><h2>{title}</h2><p>{detail}</p></section>}
function ReviewPage(){const [items,setItems]=useState<InventoryReview[]>([]),[selected,setSelected]=useState<InventoryReview|null>(null),[state,setState]=useState<"loading"|"ready"|"error"|"forbidden">("loading"),[message,setMessage]=useState(""),[submitting,setSubmitting]=useState(false),[values,setValues]=useState("{}"); const load=()=>{setState("loading"); inventoryApi.listReviews().then(r=>{setItems(r.items);setState("ready");}).catch(e=>{setState(e instanceof InventoryApiError&&e.status===403?"forbidden":"error");setMessage(e.message);});}; useEffect(load,[]); const mutate=async(action:"approve"|"correct"|"reupload")=>{if(!selected||submitting)return;setSubmitting(true);try{const value=action==="approve"?await inventoryApi.approve(selected.id):action==="reupload"?await inventoryApi.requestReupload(selected.id):await inventoryApi.correct(selected.id,JSON.parse(values));setSelected(value);await Promise.resolve(load());}catch(e){setMessage(e instanceof Error?e.message:"Unable to update review");}finally{setSubmitting(false)}}; if(state==="loading")return <Unavailable title="Loading reviews…" detail="Retrieving Inventory reviews."/>;if(state==="forbidden")return <Unavailable title="Permission denied" detail="You do not have permission to review Inventory documents."/>;if(state==="error")return <Unavailable title="Unable to load reviews" detail={message}/>; return <div className="inventory-review"><section><h2>Reviews requiring attention</h2>{items.length===0?<p className="inventory-muted">No Inventory reviews require action.</p>:<ul>{items.map(item=><li key={item.id}><button onClick={()=>setSelected(item)} className={selected?.id===item.id?"selected":""}><b>{item.reason_code}</b><small>{item.document_id}</small></button></li>)}</ul>}</section><section className="inventory-detail">{selected?<><h2>Review detail</h2><p><b>Reason:</b> {selected.reason_code}</p><pre>{JSON.stringify({original:selected.original_value,suggested:selected.suggested_value,final:selected.final_value},null,2)}</pre><textarea value={values} onChange={e=>setValues(e.target.value)} aria-label="Correction values"/><div className="inventory-actions"><button disabled={submitting} onClick={()=>void mutate("approve")}>Approve</button><button disabled={submitting} onClick={()=>void mutate("correct")}>Correct</button><button disabled={submitting} className="danger" onClick={()=>void mutate("reupload")}>Request reupload</button></div>{message&&<p className="inventory-error">{message}</p>}</>:<p className="inventory-muted">Select a review to inspect it.</p>}</section></div>}
function localBusinessDate(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const part=(kind:string)=>parts.find(value=>value.type===kind)?.value||"";return part("year")+"-"+part("month")+"-"+part("day")}
function ReportsPage(){const [item,setItem]=useState<InventoryExport|null>(null),[state,setState]=useState<"loading"|"ready"|"missing"|"error"|"forbidden">("loading"),[message,setMessage]=useState(""),[submitting,setSubmitting]=useState(false);const date=localBusinessDate();const load=()=>{setState("loading");inventoryApi.getExport(date).then(v=>{setItem(v);setState("ready")}).catch(e=>{const x=e as InventoryApiError;if(x.status===404)setState("missing");else{setState(x.status===403?"forbidden":"error");setMessage(x.message)}})};useEffect(load,[]);const run=async()=>{if(submitting)return;setSubmitting(true);try{setItem(await inventoryApi.exportDay(date));setState("ready")}catch(e){setState("error");setMessage(e instanceof Error?e.message:"Unable to export") }finally{setSubmitting(false)}};if(state==="loading")return <Unavailable title="Loading exports…" detail="Reading finalized Inventory export state."/>;if(state==="forbidden")return <Unavailable title="Permission denied" detail="You do not have permission to export Inventory reports."/>;if(state==="error")return <section className="inventory-empty"><h2>Unable to export report</h2><p>{message}</p><button disabled={submitting} onClick={()=>void run()}>Retry export</button></section>;return <section className="inventory-daily"><h2>Inventory reports · {date}</h2>{state==="missing"?<p className="inventory-muted">No export exists yet for this finalized day.</p>:<><p className={item?.status==="completed"?"inventory-ready":"inventory-error"}>{item?.status}</p><p>Main workbook: {item?.main_drive_file_id||"pending"}</p><p>Daily backup: {item?.backup_drive_file_id||"pending"}</p><p>Archive movement: {item?.archive_status||"pending"}</p><p>Generated: {item?.completed_at||"pending"}</p>{item?.error_code?<p className="inventory-error">Export error: {item.error_code}</p>:null}{item?.archive_error_code?<p className="inventory-error">Archive error: {item.archive_error_code}</p>:null}</>}<button disabled={submitting||item?.status==="completed"} onClick={()=>void run()}>{submitting?"Exporting…":"Export finalized day"}</button></section>}

function DailyPage(){const [run,setRun]=useState<InventoryDailyRun|null>(null),[state,setState]=useState<"loading"|"ready"|"missing"|"error"|"forbidden">("loading"),[message,setMessage]=useState(""),[submitting,setSubmitting]=useState(false);const date=localBusinessDate();const load=()=>{setState("loading");inventoryApi.getDailyRun(date).then(value=>{setRun(value);setState("ready")}).catch(error=>{const e=error as InventoryApiError;if(e.status===404)setState("missing");else{setState(e.status===403?"forbidden":"error");setMessage(e.message)}})};useEffect(load,[]);const finalize=async(force=false)=>{if(submitting)return;const reason=force?window.prompt("Reason for forced finalization")||undefined:undefined;if(force&&!reason)return;setSubmitting(true);try{setRun(await inventoryApi.finalizeDailyRun(date,force,reason));setState("ready")}catch(error){setState("error");setMessage(error instanceof Error?error.message:"Unable to finalize")}finally{setSubmitting(false)}};if(state==="loading")return <Unavailable title="Loading daily readiness…" detail="Checking Inventory documents and review blockers."/>;if(state==="forbidden")return <Unavailable title="Permission denied" detail="You do not have permission to view Inventory daily finalization."/>;if(state==="missing")return <Unavailable title="Today has not been checked" detail="The Inventory scheduler creates today's run at 16:30 ICT."/>;if(state==="error")return <Unavailable title="Unable to finalize daily run" detail={message}/>;return <section className="inventory-daily"><h2>Daily finalization · {run?.business_date}</h2><p className={run?.ready?"inventory-ready":"inventory-error"}>{run?.finalized?"Finalized":run?.ready?"Ready to finalize":"Blockers remain"}</p>{run?.blockers.length?<ul>{run.blockers.map((blocker,index)=><li key={blocker.code+"-"+index}>{blocker.code}</li>)}</ul>:<p className="inventory-muted">All documents, reviews and committed transactions are complete.</p>}<div className="inventory-actions"><button disabled={submitting||!run?.ready||run.finalized} onClick={()=>void finalize(false)}>Finalize day</button><button disabled={submitting||run?.finalized} className="danger" onClick={()=>void finalize(true)}>Force finalize</button></div></section>}
export function formatInventoryMaterialDate(value:string|null){if(!value)return "Chưa có dữ liệu";const parsed=new Date(value);if(Number.isNaN(parsed.getTime()))return value;return new Intl.DateTimeFormat("vi-VN",{timeZone:"Asia/Ho_Chi_Minh",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(parsed)}
export function MaterialsPage(){
  const [items,setItems]=useState<InventoryMaterial[]>([]),[candidates,setCandidates]=useState<InventoryMaterialCandidate[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busyId,setBusyId]=useState<string|null>(null),[query,setQuery]=useState("");
  const load=async()=>{setError("");try{const [materials,pending]=await Promise.all([inventoryMaterialApi.list(),inventoryMaterialApi.candidates()]);setItems(materials.items);setCandidates(pending.items)}catch(e){setError(e instanceof Error?e.message:"Không thể tải danh mục vật tư")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const perform=async(id:string,operation:()=>Promise<unknown>)=>{setBusyId(id);setError("");try{await operation();await load()}catch(e){setError(e instanceof Error?e.message:"Không thể cập nhật vật tư")}finally{setBusyId(null)}};
  const approve=(candidate:InventoryMaterialCandidate,itemId?:string)=>perform(candidate.id,()=>inventoryMaterialApi.approve(candidate.id,itemId?{item_id:itemId}:{canonical_name:candidate.suggested_canonical_name||candidate.raw_name}));
  const filteredItems=useMemo(()=>{const needle=query.trim().toLocaleLowerCase("vi");if(!needle)return items;return items.filter(item=>[item.canonical_name,item.category||"",...item.aliases,...item.sheet_keys].some(value=>value.toLocaleLowerCase("vi").includes(needle)))},[items,query]);
  const aliasCount=items.reduce((total,item)=>total+item.aliases.length,0);
  return <section className="inventory-materials inventory-materials-redesign">
    <div className="inventory-materials-hero"><div><p className="inventory-kicker">DANH MỤC INVENTORY</p><h2>Nguyên vật liệu</h2><p>Quản lý tên chuẩn, tên gọi khác và dữ liệu nhận diện từ workbook kiểm kho.</p></div><span>{items.length} vật tư</span></div>
    <div className="inventory-material-summary" aria-label="Tóm tắt danh mục vật tư"><article><span>Đang hoạt động</span><strong>{items.filter(item=>item.active).length}</strong><small>Vật tư được phép đối soát</small></article><article><span>Tên gọi khác</span><strong>{aliasCount}</strong><small>Alias đã được xác nhận</small></article><article><span>Cần xem xét</span><strong>{candidates.length}</strong><small>Vật tư mới hoặc có thể đổi tên</small></article></div>
    {error?<div className="inventory-material-error" role="alert"><b>Không thể hoàn tất thao tác</b><span>{error}</span><button type="button" onClick={()=>void load()}>Thử lại</button></div>:null}
    <div className="inventory-material-grid">
      <article className="inventory-material-registry"><div className="inventory-material-section-heading"><div><h3>Danh sách vật tư chuẩn</h3><p>Dùng tên chuẩn này khi Gemini đối chiếu dữ liệu trong Google Sheet.</p></div><label><span className="sr-only">Tìm vật tư</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Tìm theo tên, nhóm hoặc mã…"/></label></div>
        <div className="inventory-material-table-wrap"><table><thead><tr><th>Vật tư</th><th>Phân loại</th><th>Đơn vị chuẩn</th><th>Trạng thái</th></tr></thead><tbody>{loading?<tr><td colSpan={4} className="inventory-material-empty">Đang tải danh mục…</td></tr>:filteredItems.length===0?<tr><td colSpan={4} className="inventory-material-empty">{query?"Không tìm thấy vật tư phù hợp.":"Chưa có vật tư nào trong danh mục."}</td></tr>:filteredItems.map(item=><tr key={item.material_id}><td><b>{item.canonical_name}</b><small><span>Mã Sheet:</span> {item.sheet_keys.join(", ")||"Chưa có"}</small><small><span>Tên khác:</span> {item.aliases.join(", ")||"Chưa có"}</small></td><td><span className="inventory-material-category">{item.category||"Chưa phân loại"}</span></td><td><b>{item.preferred_unit||"Chưa đặt"}</b><small>{item.canonical_dimension||"Chưa có quy cách"}</small><small>{item.package_conversions.map(value=>value.package_name+" = "+value.canonical_value+" "+value.canonical_unit).join(" · ")||"Chưa có quy đổi bao gói"}</small></td><td><span className={item.active?"inventory-material-active":"inventory-material-inactive"}>{item.active?"Đang dùng":"Tạm ngưng"}</span><small>Cập nhật {formatInventoryMaterialDate(item.last_seen_at)}</small></td></tr>)}</tbody></table></div>
      </article>
      <aside className="inventory-material-review"><div className="inventory-material-section-heading"><div><h3>Hàng đợi xem xét</h3><p>Xác nhận trước khi vật tư mới hoặc tên gọi khác được đưa vào danh mục.</p></div><span className="inventory-material-count">{candidates.length}</span></div>{loading?<div className="inventory-material-review-empty">Đang kiểm tra dữ liệu mới…</div>:candidates.length===0?<div className="inventory-material-review-empty"><b>Không có mục chờ xử lý</b><span>Danh mục hiện đã được cập nhật đầy đủ.</span></div>:candidates.map(candidate=><section className="inventory-material-candidate" key={candidate.id}><div className="inventory-material-candidate-title"><span className={"inventory-material-candidate-kind "+candidate.status}>{candidate.status==="possible_rename"?"Có thể đổi tên":candidate.status==="ambiguous"?"Chưa rõ":"Vật tư mới"}</span><strong>{candidate.raw_name}</strong></div><dl><div><dt>Mã Sheet</dt><dd>{candidate.sheet_item_key||"—"}</dd></div><div><dt>Nhóm</dt><dd>{candidate.category||"Chưa phân loại"}</dd></div><div><dt>Độ tin cậy</dt><dd>{Math.round(candidate.confidence*100)}%</dd></div></dl>{candidate.suggested_canonical_name?<p className="inventory-material-suggestion">Gợi ý ghép với <b>{candidate.suggested_canonical_name}</b></p>:null}{candidate.reasons.length?<details><summary>Vì sao cần xem xét?</summary><ul>{candidate.reasons.map((reason,index)=><li key={index}>{reason}</li>)}</ul></details>:null}<div className="inventory-material-actions">{candidate.status==="possible_rename"&&candidate.suggested_item_id?<><button disabled={busyId===candidate.id} onClick={()=>void approve(candidate,candidate.suggested_item_id||undefined)}>Xác nhận tên gọi</button><button className="secondary" disabled={busyId===candidate.id} onClick={()=>void perform(candidate.id,()=>inventoryMaterialApi.approve(candidate.id,{canonical_name:candidate.raw_name}))}>Tạo vật tư riêng</button><button className="text-danger" disabled={busyId===candidate.id} onClick={()=>void perform(candidate.id,()=>inventoryMaterialApi.reject(candidate.id))}>Từ chối gợi ý</button></>:<><button disabled={busyId===candidate.id} onClick={()=>void approve(candidate)}>Tạo vật tư</button>{candidate.suggested_item_id?<button className="secondary" disabled={busyId===candidate.id} onClick={()=>void approve(candidate,candidate.suggested_item_id||undefined)}>Ghép với vật tư có sẵn</button>:null}<button className="text-button" disabled={busyId===candidate.id} onClick={()=>void perform(candidate.id,()=>inventoryMaterialApi.ignore(candidate.id))}>Bỏ qua</button></>}</div></section>)}</aside>
    </div>
  </section>
}

export function InventoryApp({ embedded = false, initialPage }: { embedded?: boolean; initialPage?: InventoryPage } = {}){const [page,setPage]=useState<Page>(()=>initialPage||pageForPath(window.location.pathname));const content=useMemo(()=>page==="review"?<ReviewPage/>:page==="inbox"?<Unavailable title="Inventory Inbox" detail="Inbox document monitoring will appear when an Inventory source-list endpoint is available."/>:page==="materials"?<MaterialsPage/>:page==="daily"?<DailyPage/>:page==="reports"?<ReportsPage/>:page==="settings"?<InventoryDailySheetSettings/>:<Unavailable title="Inventory dashboard" detail="Operational Inventory data will appear here as Inventory APIs become available."/>,[page]);return <main className={"inventory-shell"+(embedded?" inventory-shell--embedded":"")}>{!embedded?<header><a href="/" className="inventory-brand">Creative assets</a><span>Inventory</span></header>:null}<nav className="inventory-nav" aria-label="Inventory navigation">{links.map(([key,label,href])=>embedded?<button key={key} type="button" onClick={()=>setPage(key)} aria-current={page===key?"page":undefined}>{label}</button>:<a key={key} href={href} aria-current={page===key?"page":undefined}>{label}</a>)}</nav><div className="inventory-content">{content}</div></main>}
