from datetime import datetime,timezone
from uuid import uuid4
from sqlalchemy import CheckConstraint,DateTime,ForeignKeyConstraint,Index,Integer,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.core.database import Base
def now():return datetime.now(timezone.utc)
class VideoGenerationRunModel(Base):
 __tablename__="video_generation_runs"
 __table_args__=(ForeignKeyConstraint(["tenant_id","output_asset_id"],["assets.tenant_id","assets.id"],name="fk_video_generation_output",ondelete="RESTRICT"),UniqueConstraint("tenant_id","id",name="uq_video_generation_tenant_id"),UniqueConstraint("tenant_id","created_by_user_id","client_request_id",name="uq_video_generation_client_request"),CheckConstraint("provider = 'dola'",name="ck_video_generation_provider"),CheckConstraint("status IN ('queued','preparing','submitted','running','submission_unknown','storing','completed','failed','cancelled')",name="ck_video_generation_status"),Index("ix_video_generation_tenant_status","tenant_id","status","created_at"))
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid4()));tenant_id:Mapped[str]=mapped_column(String(255),nullable=False);provider:Mapped[str]=mapped_column(String(32),nullable=False,default="dola");provider_model:Mapped[str]=mapped_column(String(128),nullable=False);prompt:Mapped[str]=mapped_column(Text,nullable=False);aspect_ratio:Mapped[str]=mapped_column(String(16),nullable=False);duration_seconds:Mapped[int]=mapped_column(Integer,nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="queued");request_fingerprint:Mapped[str]=mapped_column(String(64),nullable=False);client_request_id:Mapped[str]=mapped_column(String(200),nullable=False);created_by_user_id:Mapped[str]=mapped_column(String(255),nullable=False);gateway_generation_id:Mapped[str|None]=mapped_column(String(255));output_asset_id:Mapped[str|None]=mapped_column(String(36));last_error_code:Mapped[str|None]=mapped_column(String(100));last_error_message:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now);submitted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class VideoGenerationReferenceModel(Base):
 __tablename__="video_generation_references"
 __table_args__=(ForeignKeyConstraint(["tenant_id","run_id"],["video_generation_runs.tenant_id","video_generation_runs.id"],name="fk_video_generation_reference_run",ondelete="CASCADE"),ForeignKeyConstraint(["tenant_id","asset_id"],["assets.tenant_id","assets.id"],name="fk_video_generation_reference_asset",ondelete="RESTRICT"),UniqueConstraint("run_id","position",name="uq_video_generation_reference_position"))
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid4()));tenant_id:Mapped[str]=mapped_column(String(255),nullable=False);run_id:Mapped[str]=mapped_column(String(36),nullable=False);asset_id:Mapped[str]=mapped_column(String(36),nullable=False);position:Mapped[int]=mapped_column(Integer,nullable=False)
