import { useEffect, useState } from "react";
import { managementApi, type Scope, type Share } from "./api";
export function canManagePublicReview(permissions: string[]) { return permissions.includes("public_review.manage"); }
export function defaultShareExpiryLocal(now = new Date()) {
 const value = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
 const local = new Date(value.getTime() - value.getTimezoneOffset() * 60 * 1000);
 return local.toISOString().slice(0, 16);
}
function future(value: string) { return !value || new Date(value).getTime() > Date.now(); }
function LinkResult({ url, onDismiss }: { url: string; onDismiss: () => void }) { const [copied, setCopied] = useState(false); return <div className="public-review-link-result"><strong>Anyone with this link can access this review.</strong><code>{url}</code><button onClick={async()=>{await navigator.clipboard?.writeText(url);setCopied(true);}}>{copied ? "Copied" : "Copy link"}</button><button onClick={onDismiss}>Dismiss</button></div>; }
export function PublicReviewManagementDialog({ initialScope, availableScopes, onClose }: { initialScope: Scope; availableScopes: Scope[]; onClose: () => void }) {
 const [shares,setShares]=useState<Share[]>([]),[name,setName]=useState("Review"),[scopes,setScopes]=useState<Scope[]>([initialScope]),[comments,setComments]=useState(true),[download,setDownload]=useState(false),[expires,setExpires]=useState(()=>defaultShareExpiryLocal()),[oneTime,setOneTime]=useState<string>(),[editing,setEditing]=useState<Share>(),[error,setError]=useState("");
 const load=()=>managementApi.list().then(value=>setShares(value.items)).catch(()=>setError("Unable to load review shares.")); useEffect(()=>{load();},[]);
 const save=async()=>{if(!name.trim()||!scopes.length||!future(expires)){setError("Enter a review name, at least one folder, and a future expiration.");return;} if(new Set(scopes.map(x=>x.external_source_id+":"+x.folder_external_id)).size!==scopes.length){setError("Folder scopes must be unique.");return;} try { const value={name:name.trim(),scopes,allow_comments:comments,allow_download:download,expires_at:expires?new Date(expires).toISOString():null}; const share=editing?await managementApi.update(editing.id,value):await managementApi.create(value); setOneTime(share.share_url); setEditing(undefined);load(); }catch{setError("Unable to save this review share.");}};
 const edit=(share:Share)=>{setEditing(share);setName(share.name);setScopes(share.scopes);setComments(share.allow_comments);setDownload(share.allow_download);setExpires(share.expires_at?share.expires_at.slice(0,16):"");};
 return <div className="public-review-management-backdrop" role="dialog" aria-modal="true" aria-label="Share folder for review"><section className="public-review-management"><header><h2>{editing?"Edit review share":"Share for review"}</h2><button onClick={onClose} aria-label="Close">×</button></header>{oneTime?<LinkResult url={oneTime} onDismiss={()=>setOneTime(undefined)}/>:<><label>Review name<input value={name} onChange={event=>setName(event.target.value)} maxLength={255}/></label><fieldset><legend>Folder scopes</legend>{scopes.map(scope=><div key={scope.external_source_id+scope.folder_external_id}>{scope.folder_name||scope.folder_external_id}<button onClick={()=>setScopes(value=>value.filter(item=>item!==scope))}>Remove</button></div>)}{availableScopes.filter(option=>!scopes.some(scope=>scope.external_source_id===option.external_source_id&&scope.folder_external_id===option.folder_external_id)).map(option=><button key={option.external_source_id+option.folder_external_id} onClick={()=>setScopes(value=>[...value,option])}>Add {option.folder_name||option.folder_external_id}</button>)}</fieldset><label><input type="checkbox" checked={comments} onChange={event=>setComments(event.target.checked)}/> Allow comments</label><label><input type="checkbox" checked={download} onChange={event=>setDownload(event.target.checked)}/> Allow download policy</label><small>Downloads are not currently provided by the public portal.</small><label>Expiration (optional)<input type="datetime-local" value={expires} onChange={event=>setExpires(event.target.value)}/></label><button onClick={()=>void save()}>{editing?"Save settings":"Create review link"}</button></>}{error&&<p role="alert">{error}</p>}<hr/><h3>Existing shares</h3>{shares.map(share=><article key={share.id}><b>{share.name}</b> · {share.status}<div>{share.scopes.map(scope=><span key={scope.external_source_id+scope.folder_external_id}>{scope.folder_name||scope.folder_external_id} </span>)}</div>{share.status!=="revoked"&&<><button onClick={()=>edit(share)}>Edit</button><button onClick={async()=>{if(confirm("Old link and public sessions will stop. Rotate this link?")){const value=await managementApi.rotate(share.id);setOneTime(value.share_url);load();}}}>Rotate link</button><button onClick={async()=>{if(confirm("Public access and existing sessions will stop. Revoke this link?")){await managementApi.revoke(share.id);load();}}}>Revoke</button></>}</article>)}</section></div>;
}
