import { LEGAL_CONFIG as C } from "../config/legal";
import "../../styles/legal.css";

type Section = { id: string; title: string; children: React.ReactNode };
const Link = ({to,children}: {to:string;children:React.ReactNode}) => <a href={to}>{children}</a>;
function Layout({title, description, sections}:{title:string;description:string;sections:Section[]}) {
  document.title = `${title} | ${C.applicationName}`;
  return <main className="legal-page"><header className="legal-header"><a className="legal-brand" href="/">{C.brandName}<span>{C.applicationName}</span></a><a href="/">Back to Creative Asset Manager</a></header><article className="legal-article"><p className="legal-kicker">{C.brandName}</p><h1>{title}</h1><p className="legal-effective">Effective date: {C.effectiveDate}</p><p className="legal-intro">{description}</p><nav className="legal-toc" aria-label="Table of contents"><strong>Contents</strong>{sections.map(s=><a key={s.id} href={`#${s.id}`}>{s.title}</a>)}</nav>{sections.map(s=><section id={s.id} key={s.id}><h2>{s.title}</h2>{s.children}</section>)}<p className="legal-top"><a href="#top">Back to top</a></p></article><footer className="legal-footer"><span>© {C.brandName} · {C.websiteUrl}</span><span><Link to="/privacy-policy">Privacy Policy</Link> · <Link to="/terms-of-service">Terms of Service</Link></span></footer></main>;
}
const Bullets=({items}:{items:string[]})=><ul>{items.map(i=><li key={i}>{i}</li>)}</ul>;
export function PrivacyPolicyPage(){const sections:Section[]=[
{id:"information",title:"1. Information We Collect",children:<><h3>Account and identity information</h3><Bullets items={["Name, email address, profile image, identity-provider identifier, organization membership, authentication and session information, roles and permissions."]}/><h3>Google user data</h3><p>When a user connects Google Drive, we may request read-only access using <code>https://www.googleapis.com/auth/drive.readonly</code>. We may access file and folder names, identifiers, MIME types, sizes, timestamps, hierarchy, thumbnails, previews, metadata, and authorized file contents. We do not modify or delete originals.</p><h3>Imported and technical data</h3><p>We may store managed copies, previews, dimensions, descriptions, labels, tags, classifications, search indexes, vector representations, automated results, status and errors, plus IP address, device information, timestamps and diagnostic logs.</p></>},
{id:"use",title:"2. How We Use Information",children:<p>We use information to authenticate users, maintain sessions, connect authorized accounts, display and synchronize assets, generate previews, analyze and search content, enforce permissions, diagnose problems, prevent abuse, support customers and comply with law. Google data is not used for advertising, profiling, credit decisions or sale.</p>},
{id:"limited-use",title:"3. Google API Limited Use",children:<p>Our use and transfer of information received from Google APIs adheres to the Google API Services User Data Policy and Limited Use requirements. Google data is not sold or transferred to advertising platforms or data brokers. Human access is restricted to user-authorized, security, support, legal, or aggregated non-identifying purposes.</p>},
{id:"ai",title:"4. Automated and AI Processing",children:<p>Authorized features may generate descriptions, tags, categories, search metadata and similarity information. Output may be incomplete or inaccurate. Desify does not use Google Drive data to train a general-purpose AI model. Providers process content only to provide requested functionality.</p>},
{id:"sharing",title:"5. Sharing",children:<p>Assets may be available to authorized workspace users. Service providers may process data for infrastructure, storage, databases, search, security, monitoring, email and analysis. We may disclose information for legal, security, fraud, rights protection or business transactions. We do not sell personal or Google data.</p>},
{id:"security",title:"6. Storage and Security",children:<p>We use encrypted connections, access controls, role-based authorization, restricted production access, encrypted OAuth credentials, logging, credential rotation and recovery controls. No system is completely secure.</p>},
{id:"retention",title:"7. Data Retention",children:<p>We retain information as reasonably necessary to provide the Service, maintain accounts, process requests, resolve disputes, secure systems and comply with law. Tokens may be retained while a connection is active. Deletion follows active-system processes; backups may persist temporarily.</p>},
{id:"disconnect",title:"8. Disconnecting Google Drive",children:<p>Users may disconnect the source, remove the connection, or revoke access in Google Account security settings. Revocation prevents new access but does not delete already imported assets; delete those assets or submit a request.</p>},
{id:"rights",title:"9. Access and Deletion Requests",children:<p>Requests for access, correction, deletion, export, restriction, objection or withdrawal may be sent to {C.privacyEmail}. Include enough information to verify identity and identify the workspace.</p>},
{id:"cookies",title:"10. Cookies and Sessions",children:<p>We use necessary cookies for authentication, secure sessions, OAuth protection, essential settings and security. We do not use Google data for advertising cookies.</p>},
{id:"children",title:"11. Children and Third Parties",children:<p>The Service is for business users and is not directed to children under 13. Third-party platforms such as Google have their own terms and privacy policies.</p>},
{id:"changes",title:"12. Changes",children:<p>We may update this policy when functionality, providers, data practices or law changes. We will update the effective date and provide notice where required.</p>},
{id:"contact",title:"13. Contact Us",children:<p>{C.brandName} / {C.legalEntityName}<br/>Privacy email: {C.privacyEmail}<br/>Address: {C.registeredAddress}<br/>Website: <a href={C.websiteUrl}>{C.websiteUrl}</a></p>},]; return <Layout title="Privacy Policy" description="This Privacy Policy explains how Creative Asset Manager collects, accesses, uses, stores, shares and protects information when users access the Service." sections={sections}/>;}
export function TermsOfServicePage(){const sections:Section[]=[
{id:"eligibility",title:"1. Eligibility and Authority",children:<p>Users must be legally capable of agreeing to these Terms. Organization users represent they have authority to bind the organization and connect authorized accounts and content.</p>},
{id:"accounts",title:"2. Accounts",children:<p>Users are responsible for accurate information, credentials, connected identity accounts, account activity and promptly reporting unauthorized access.</p>},
{id:"drive",title:"3. Google Drive Integration",children:<p>The Service may display folders, read metadata, generate previews, download authorized files, synchronize selected content and process it for search and analysis using read-only Drive access. Users must have permission to connect and process content. Google terms also apply.</p>},
{id:"workspaces",title:"4. Workspaces and Permissions",children:<p>Administrators may invite users, assign roles, connect sources, configure processing, access content and manage settings. Users must follow organization access policies.</p>},
{id:"content",title:"5. User Content",children:<p>Users retain ownership. They grant Desify a limited license to host, copy, transmit, process, transform, index, display and create technical derivatives solely to operate the Service, provide features, generate previews, analyze, search, back up, secure and support it.</p>},
{id:"responsibilities",title:"6. Responsibilities and Acceptable Use",children:<p>Users must have rights and consents for content and comply with law. They may not infringe rights, bypass controls, distribute malware, exploit vulnerabilities, disrupt infrastructure, scrape outside supported functionality, resell access, use data for advertising or process unlawful content.</p>},
{id:"ai",title:"7. Automated Analysis",children:<p>Automated systems may generate descriptions, tags, categories, indexes and similarity results. Output may contain errors and must be reviewed before legal, employment, financial, safety, publication or significant business decisions.</p>},
{id:"supported",title:"8. Supported Files",children:<p>The Service supports specified formats, sizes and capabilities. Files may be excluded, skipped as unsupported, unavailable due to provider restrictions, or present in Explorer without being importable, analyzable, indexable or previewable.</p>},
{id:"third-party",title:"9. Third-Party Services",children:<p>The Service depends on Google Drive, identity providers, infrastructure, storage, search and analysis providers. They may change or discontinue functionality and outages are outside our reasonable control.</p>},
{id:"availability",title:"10. Availability and Security",children:<p>We do not guarantee uninterrupted availability. Maintenance, updates, failures, security events and provider outages may affect the Service. Users must use reasonable security practices and report compromise or vulnerabilities.</p>},
{id:"ip",title:"11. Intellectual Property",children:<p>Except for User Content, Desify and licensors retain rights in the Service, source code, interfaces, designs, documentation, trademarks, logos and processing methods.</p>},
{id:"fees",title:"12. Fees, Suspension and Termination",children:<p>Paid features and terms will be disclosed before purchase. We may suspend or terminate access for violations, security risk, unpaid obligations, legal liability, unavailable providers or administrator removal. Content deletion follows retention practices.</p>},
{id:"liability",title:"13. Disclaimers and Limitation of Liability",children:<p>To the maximum extent permitted by law, the Service is provided “as is” and “as available.” Desify disclaims implied warranties. Desify is not liable for indirect or consequential damages; total liability will not exceed amounts paid in the preceding 12 months or the minimum liability required by law.</p>},
{id:"law",title:"14. Indemnification, Law and Changes",children:<p>Users agree to defend and indemnify Desify for User Content, unlawful use, Terms violations and unauthorized connections. These Terms are governed by the laws of Vietnam. We may update them and will update the effective date where required.</p>},
{id:"contact",title:"15. Contact",children:<p>{C.brandName} / {C.legalEntityName}<br/>Support email: {C.supportEmail}<br/>Address: {C.registeredAddress}<br/>Website: <a href={C.websiteUrl}>{C.websiteUrl}</a></p>},]; return <Layout title="Terms of Service" description="These Terms govern access to and use of Creative Asset Manager, including Asset Explorer, cloud integrations, processing and search features." sections={sections}/>;}
