import { useEffect, useMemo, useState } from "react";
type Asset={id:string;name:string;kind:"folder"|"image"|"video"|"pdf"|"document"|"other";mime_type:string;modified_at?:string};
type Tag={id:string;name:string;color:string}; type Folder={parent:Asset;children:Asset[]};
const icons={folder:"📁",image:"▧",video:"▶",pdf:"PDF",document:"DOC",other:"◇"};
export default function App(){
 const [path,setPath]=useState<Asset[]>([]),[items,setItems]=useState<Asset[]>([]),[tags,setTags]=useState<Tag[]>([]),[selected,setSelected]=useState<Set<string>>(new Set());
 const [query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function open(id="root",at?:number){setLoading(true);setError("");setSelected(new Set());try{const r=await fetch("/api/explorer/children?parent_id="+encodeURIComponent(id));if(!r.ok)throw Error((await r.json()).detail);const d:Folder=await r.json();setItems(d.children);setPath(p=>at===undefined?[...p,d.parent]:[...p.slice(0,at),d.parent])}catch(e){setError(e instanceof Error?e.message:"Unable to load folder")}finally{setLoading(false)}}
 useEffect(()=>{open();fetch("/api/tags").then(r=>r.json()).then(setTags).catch(()=>setTags([]))},[]);
 const visible=useMemo(()=>items.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())),[items,query]);
 function toggle(id:string){setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
 async function applyTag(tagId:string){const r=await fetch("/api/tags/assign",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({item_ids:[...selected],tag_id:tagId})});r.ok?setSelected(new Set()):setError("Unable to assign tag")}
 return <main className="shell"><aside><div className="brand"><b>C</b><span><strong>Creative assets</strong><small>Google Drive</small></span></div><p>SOURCES</p><button className="source" onClick={()=>open("root",0)}>◆ My Drive</button><div className="tree">{items.filter(x=>x.kind==="folder").map(x=><button key={x.id} onClick={()=>open(x.id)}>▸ {x.name}</button>)}</div><p>TAGS</p>{tags.map(t=><button className="tag" key={t.id}><i style={{background:t.color}}/>{t.name}</button>)}<div className="storage">Storage <b>42 GB / 100 GB</b><span><i/></span></div></aside><section><header><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this folder"/></label><div className="avatar">BN</div></header><nav><div>{path.map((x,i)=><button key={x.id} onClick={()=>open(x.id,i)}>{x.name}</button>)}</div><button className="upload">＋ Upload</button></nav>{error&&<div className="error">{error}</div>}<div className="title"><span><h1>{path.at(-1)?.name||"My Drive"}</h1><small>{items.length} items</small></span><b>▦　☷</b></div>{loading?<div className="state">Loading assets…</div>:<div className="grid">{visible.map(x=><article className={selected.has(x.id)?"selected":""} key={x.id}><button className="check" onClick={()=>toggle(x.id)}>{selected.has(x.id)?"✓":""}</button><button className={"preview "+x.kind} onDoubleClick={()=>x.kind==="folder"&&open(x.id)}><span>{icons[x.kind]}</span></button><div><button className="name" onDoubleClick={()=>x.kind==="folder"&&open(x.id)}>{x.name}</button><small>{x.kind==="folder"?"Folder":x.modified_at?new Date(x.modified_at).toLocaleDateString():x.mime_type}</small></div></article>)}</div>}{!loading&&!visible.length&&<div className="state">No assets found</div>}{selected.size>0&&<div className="bulk"><b>{selected.size} selected</b>{tags.map(t=><button key={t.id} onClick={()=>applyTag(t.id)}><i style={{background:t.color}}/>{t.name}</button>)}<button onClick={()=>setSelected(new Set())}>×</button></div>}</section></main>}
