from __future__ import annotations

import asyncio
import hashlib
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime, timezone

from pydantic import BaseModel, ConfigDict, Field, ValidationError
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.domain.processing.handlers import JobHandlerContext, JobHandlerResult
from app.domain.providers.contracts import (
    AiMetadataAnalysisInput,
    AiProviderError,
    OpenStoredAssetInput,
    StorageProviderError,
)
from app.domain.providers.registry import AiProviderUnavailableError
from app.modules.ai_metadata.analysis_image import AnalysisImageError, AnalysisImagePreparer
from app.modules.processing.repository import ProcessingRepository
from app.modules.realistic_review_ugc.gemini_safety import (
    deferred_rrugc_ai_retry,
    scheduled_rrugc_gemini_slot,
)
from app.modules.realistic_review_ugc.model import (
    RrugcStage2JobModel,
    RrugcStage3AnalysisModel,
)


STAGE3_ANALYSIS_VERSION = "rrugc-stage3-ugc-v2"
STAGE3_JOB_TYPE = "rrugc_stage3_analyze"

class Stage3UgcAnalysisDocument(BaseModel):
    model_config = ConfigDict(extra="forbid")

    people_count: int = Field(ge=0, le=20)
    person_visible: bool
    hat_visible: bool
    product_visible: bool
    embroidery_visible: bool
    mobile_ugc_score: float = Field(ge=0.0, le=1.0)
    photorealism_score: float = Field(ge=0.0, le=1.0)
    product_visibility_score: float = Field(ge=0.0, le=1.0)
    review_fit_score: float = Field(ge=0.0, le=1.0)
    scene_type: str = Field(default="unknown", max_length=64)
    framing_type: str = Field(default="unknown", max_length=64)
    evidence: list[str] = Field(default_factory=list, max_length=6)
    summary: str = Field(min_length=1, max_length=500)
    review_text: str | None = Field(default=None, max_length=600)


_STAGE3_SCORE_FIELDS = (
    "mobile_ugc_score",
    "photorealism_score",
    "product_visibility_score",
    "review_fit_score",
)


def normalize_stage3_metadata(metadata: Mapping[str, object]) -> dict[str, object]:
    """Normalize common structured-output drift before strict validation."""
    allowed = set(Stage3UgcAnalysisDocument.model_fields)
    normalized: dict[str, object] = {
        key: value for key, value in metadata.items() if key in allowed
    }

    for key in _STAGE3_SCORE_FIELDS:
        value = normalized.get(key)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            score = float(value)
            if 1.0 < score <= 10.0:
                score /= 10.0
            elif 10.0 < score <= 100.0:
                score /= 100.0
            normalized[key] = score

    summary = normalized.get("summary")
    if not isinstance(summary, str) or not summary.strip():
        normalized["summary"] = (
            "Visible image qualities were evaluated for realistic UGC review-card fit."
        )

    evidence = normalized.get("evidence")
    if isinstance(evidence, list) and len(evidence) > 6:
        normalized["evidence"] = evidence[:6]

    return normalized


def stage3_analysis_prompt() -> str:
    return """
You are evaluating a generated product lifestyle image for use in a realistic UGC customer-review card.
Return exactly one JSON object matching the supplied schema and no prose.

Evaluate only visible image qualities. Do not identify any person and do not infer age, ethnicity,
health, religion, politics, sexual orientation, or other sensitive traits.

The product is a hat/cap with a personalized embroidery design. Score:
- people_count / person_visible: whether at least one person is visibly present.
- hat_visible: whether a hat/cap is visibly present.
- product_visible: whether the featured product is sufficiently visible to understand what is reviewed.
- embroidery_visible: whether embroidery/design detail on the hat is visibly readable/recognizable.
- mobile_ugc_score: natural phone-photo / social UGC feel, not polished studio-ad composition.
- photorealism_score: plausible camera photograph appearance, anatomy, materials, lighting, shadows and edges.
- product_visibility_score: product prominence and clarity without requiring a close-up.
- review_fit_score: overall suitability as the hero image for a believable customer review card.

Do not penalize an image merely because it was generated by AI; judge the visible result.
A normal lifestyle crop is acceptable. Embroidery visibility is useful but not mandatory for approval.
Evidence must contain at most 6 short visible observations.

Also write review_text as 1-3 short, natural sentences in casual American English for a synthetic
customer-review card. It should sound like an ordinary hat buyer talking about everyday wear, fit,
style, or why they picked the design. Keep it specific enough to feel human, but only use details that
are visible or safely generic. Do not identify the visible person, infer demographic traits, or invent
shipping speed, customer service interactions, discounts, exact durability history, or other facts not
supported by the image. Vary both sentence count and opening style from one image to the next; do not
default to stock openings such as "Obsessed with...". Do not include a reviewer name or star rating
in review_text.
""".strip()


@dataclass(frozen=True, slots=True)
class Stage3Decision:
    status: str
    final_score: float
    reject_reasons: list[str]


def evaluate_stage3(document: Stage3UgcAnalysisDocument) -> Stage3Decision:
    reasons: list[str] = []
    if document.people_count < 1 or not document.person_visible:
        reasons.append("no_visible_person")
    if not document.hat_visible and not document.product_visible:
        reasons.append("product_not_visible")
    final_score = round(
        0.30 * document.review_fit_score
        + 0.25 * document.mobile_ugc_score
        + 0.25 * document.product_visibility_score
        + 0.20 * document.photorealism_score,
        4,
    )
    return Stage3Decision(
        status="ready" if not reasons else "rejected",
        final_score=final_score,
        reject_reasons=reasons,
    )


REVIEWER_FIRST_NAMES = (
    "Ashley", "Amanda", "Brittany", "Brooke", "Caitlin", "Chelsea", "Emily", "Erin",
    "Hannah", "Jessica", "Katie", "Lauren", "Megan", "Nicole", "Rachel", "Samantha",
    "Taylor", "Allison", "Morgan", "Casey", "Jordan", "Alex", "Chris", "Drew",
    "Ethan", "Jake", "Jason", "Josh", "Kevin", "Kyle", "Logan", "Matt",
    "Mike", "Nathan", "Ryan", "Scott", "Tyler", "Zach", "Ben", "Cole",
)


def reviewer_name_for_analysis(analysis_id: str) -> str:
    digest = hashlib.sha256(analysis_id.encode("utf-8")).digest()
    first_name = REVIEWER_FIRST_NAMES[digest[0] % len(REVIEWER_FIRST_NAMES)]
    last_initial = chr(ord("A") + (digest[1] % 26))
    return f"{first_name} {last_initial}."


def star_rating_for_analysis(analysis_id: str) -> int:
    bucket = hashlib.sha256(("stars:" + analysis_id).encode("utf-8")).digest()[0]
    if bucket < 205:
        return 5
    if bucket < 248:
        return 4
    return 3


_REVIEW_SHORT_EMBROIDERY = (
    "Clean embroidery, easy colors, and a really wearable everyday look.",
    "Fun detail without feeling too loud — exactly what I want from a casual cap.",
    "The stitching gives this hat just enough personality to stand out.",
    "Simple, playful, and easy to work into a casual outfit.",
    "A nice grab-and-go cap with a little more character than a basic one.",
    "The embroidered front is subtle enough for everyday wear but still feels special.",
    "Easy to style, and the front detail keeps the whole look from feeling plain.",
    "Good balance of casual and fun; the embroidery is the part that makes it.",
)

_REVIEW_SHORT_GENERIC = (
    "Simple, clean, and really easy to style for an everyday look.",
    "A relaxed cap that works without making the outfit feel overdone.",
    "Easy colors, casual shape, and exactly the kind of hat I would reach for often.",
    "Low-key, wearable, and easy to pair with basic weekend outfits.",
    "A solid everyday cap with a clean look and just enough personality.",
    "Casual in the best way — easy to throw on and still looks put together.",
    "This has the kind of simple shape that works with almost any casual outfit.",
    "Clean and uncomplicated, which is exactly why this one works so well.",
)

_REVIEW_OPENINGS = (
    "Exactly the kind of cap I reach for when I want something casual.",
    "The whole look feels laid-back without looking plain.",
    "This one has an easy everyday vibe that works really well.",
    "Simple at first glance, but there is enough detail to keep it interesting.",
    "I like how effortless this cap looks with a basic outfit.",
    "A fun hat that still feels easy enough for regular wear.",
    "The color and front design feel nicely balanced on this one.",
    "Low-key enough for everyday wear, but it still has some character.",
    "This is the kind of hat that makes a simple outfit feel more finished.",
    "Really like the relaxed shape and uncomplicated styling here.",
    "Such an easy casual piece to build an outfit around.",
    "For an everyday cap, this hits a nice balance between simple and distinctive.",
)

_REVIEW_EMBROIDERY_DETAILS = (
    "The embroidered detail stands out nicely without taking over the whole cap.",
    "The stitching gives the front a more personal feel without looking oversized.",
    "The embroidery adds enough contrast to make the design noticeable right away.",
    "I like that the front detail feels playful while the rest of the hat stays simple.",
    "The stitched design is what keeps it from feeling like just another basic cap.",
    "The embroidery reads clearly and adds a nice focal point to the front.",
    "That little bit of stitched detail gives the whole hat more personality.",
    "The front design feels intentional and still keeps the overall look clean.",
    "The embroidery makes it feel a little more special without making it hard to style.",
    "The stitched front works especially well with the otherwise relaxed look.",
)

_REVIEW_GENERIC_DETAILS = (
    "The overall design stays clean and does not feel too busy.",
    "The shape looks easy to pair with jeans, tees, or a casual weekend outfit.",
    "The colors feel straightforward enough to work into an everyday wardrobe.",
    "There is enough visual interest to keep it from feeling like a plain basic cap.",
    "The front stays noticeable without dominating the rest of the look.",
    "It has that effortless, wear-with-anything kind of feel I like in a cap.",
    "The proportions look balanced and keep the style feeling relaxed.",
    "I like how the design adds personality while the rest stays uncomplicated.",
    "The clean finish makes it easy to imagine wearing with a lot of casual looks.",
    "Nothing feels overworked here, which makes the hat much easier to style.",
)

_REVIEW_CLOSINGS = (
    "I would reach for this one a lot.",
    "Definitely an easy everyday pick.",
    "Good balance of fun and wearable.",
    "This would be an easy weekend go-to.",
    "It works especially well for casual days.",
    "A solid choice when I want something simple with a little personality.",
    "Easy to wear and easy to style.",
    "I can see this getting a lot of rotation.",
    "Just enough detail to keep it interesting.",
    "A nice grab-and-go hat for a relaxed outfit.",
)


def compose_review_text(*, analysis_id: str, embroidery_visible: bool) -> str:
    """Build stable synthetic review copy with deliberately varied cadence and length."""
    digest = hashlib.sha256(("review-copy:" + analysis_id).encode("utf-8")).digest()
    length_bucket = digest[0] % 100
    short_pool = _REVIEW_SHORT_EMBROIDERY if embroidery_visible else _REVIEW_SHORT_GENERIC
    detail_pool = _REVIEW_EMBROIDERY_DETAILS if embroidery_visible else _REVIEW_GENERIC_DETAILS

    if length_bucket < 25:
        return short_pool[digest[1] % len(short_pool)]

    opening = _REVIEW_OPENINGS[digest[1] % len(_REVIEW_OPENINGS)]
    detail = detail_pool[digest[2] % len(detail_pool)]
    if length_bucket < 75:
        return f"{opening} {detail}"

    closing = _REVIEW_CLOSINGS[digest[3] % len(_REVIEW_CLOSINGS)]
    return f"{opening} {detail} {closing}"


def review_text_for_analysis(
    document: Stage3UgcAnalysisDocument,
    analysis_id: str,
) -> str:
    # Gemini still returns a short review observation as part of structured
    # analysis, but final customer-facing copy is composed locally. This keeps
    # wording stable across refreshes and prevents repeated model openers from
    # propagating across an entire review grid.
    return compose_review_text(
        analysis_id=analysis_id,
        embroidery_visible=document.embroidery_visible,
    )


class RrugcStage3Service:
    def __init__(self, session: Session):
        self.session = session

    def get_analysis(
        self, tenant_id: str, stage2_job_id: str
    ) -> RrugcStage3AnalysisModel | None:
        return self.session.scalar(
            select(RrugcStage3AnalysisModel).where(
                RrugcStage3AnalysisModel.tenant_id == tenant_id,
                RrugcStage3AnalysisModel.stage2_job_id == stage2_job_id,
            )
        )

    def ensure_analysis_for_job(
        self,
        *,
        tenant_id: str,
        stage2_job: RrugcStage2JobModel,
        force: bool = False,
    ) -> tuple[RrugcStage3AnalysisModel, bool]:
        if (
            stage2_job.tenant_id != tenant_id
            or stage2_job.status != "completed"
            or not stage2_job.output_remote_file_id
        ):
            raise ValueError("Stage 2 output is not eligible for Stage 3 analysis.")

        row = self.get_analysis(tenant_id, stage2_job.id)
        created = row is None
        now = datetime.now(timezone.utc)
        if row is None:
            row = RrugcStage3AnalysisModel(
                tenant_id=tenant_id,
                stage2_job_id=stage2_job.id,
                output_content_hash=stage2_job.output_content_hash,
                analysis_version=STAGE3_ANALYSIS_VERSION,
                analysis_revision=1,
                status="queued",
                queued_at=now,
            )
            self.session.add(row)
            self.session.flush()
        else:
            output_changed = (
                row.output_content_hash != stage2_job.output_content_hash
                or row.analysis_version != STAGE3_ANALYSIS_VERSION
            )
            if not force and not output_changed and row.status in {
                "queued",
                "analyzing",
                "ready",
                "rejected",
            }:
                return row, False
            row.analysis_revision = max(1, int(row.analysis_revision or 0) + 1)
            row.output_content_hash = stage2_job.output_content_hash
            row.analysis_version = STAGE3_ANALYSIS_VERSION
            row.status = "queued"
            row.queued_at = now
            row.started_at = None
            row.completed_at = None
            row.reviewer_name = None
            row.star_rating = None
            row.review_text = None
            row.review_generated_at = None
            row.last_error_code = None
            row.last_error_message = None

        processing_job, processing_created = ProcessingRepository(self.session).create_job_once(
            tenant_id=tenant_id,
            job_type=STAGE3_JOB_TYPE,
            entity_type="rrugc_stage3_analysis",
            entity_id=row.id,
            idempotency_key=(
                f"rrugc-stage3-analyze:{row.id}:{row.analysis_revision}"
            ),
            payload={
                "analysis_id": row.id,
                "stage2_job_id": stage2_job.id,
                "analysis_revision": row.analysis_revision,
            },
            priority=15,
            max_attempts=4,
        )
        row.processing_job_id = processing_job.id
        self.session.flush()
        return row, bool(created or processing_created)


class RrugcStage3AnalyzeJobHandler:
    def __call__(self, context: JobHandlerContext) -> JobHandlerResult:
        try:
            return asyncio.run(self._execute(context))
        except ValidationError as exc:
            context.logger.warning(
                "rrugc_stage3_analysis_invalid_document",
                extra={
                    "analysis_id": context.job.entity_id,
                    "tenant_id": context.job.tenant_id,
                    "validation_errors": exc.errors(include_input=False),
                },
            )
            self._mark_error(
                context,
                "stage3_analysis_invalid_document",
                "Stage 3 analyzer returned an invalid document.",
            )
            return JobHandlerResult.retryable(
                "stage3_analysis_invalid_document",
                "Stage 3 analyzer returned an invalid document.",
            )
        except AnalysisImageError as exc:
            self._mark_error(context, exc.code, str(exc))
            outcome = (
                JobHandlerResult.retryable
                if exc.retryable
                else JobHandlerResult.non_retryable
            )
            return outcome(exc.code, str(exc))
        except StorageProviderError as exc:
            self._mark_error(context, exc.code, "Stage 3 image could not be opened.")
            outcome = (
                JobHandlerResult.retryable
                if exc.retryable
                else JobHandlerResult.non_retryable
            )
            return outcome(exc.code, "Stage 3 image could not be opened.")
        except AiProviderUnavailableError:
            self._mark_error(
                context,
                "ai_provider_unavailable",
                "Stage 3 analyzer provider is unavailable.",
            )
            return JobHandlerResult.non_retryable(
                "ai_provider_unavailable",
                "Stage 3 analyzer provider is unavailable.",
            )
        except AiProviderError as exc:
            self._mark_error(context, exc.code, "Stage 3 analyzer failed.")
            deferred = deferred_rrugc_ai_retry(
                exc,
                message="Stage 3 analyzer is temporarily unavailable.",
            )
            if deferred is not None:
                return deferred
            outcome = (
                JobHandlerResult.retryable
                if exc.retryable
                else JobHandlerResult.non_retryable
            )
            return outcome(exc.code, "Stage 3 analyzer failed.")
        except Exception:
            context.logger.exception(
                "rrugc_stage3_analysis_failed",
                extra={
                    "analysis_id": context.job.entity_id,
                    "tenant_id": context.job.tenant_id,
                },
            )
            self._mark_error(
                context,
                "stage3_analysis_internal_error",
                "Stage 3 analysis failed.",
            )
            return JobHandlerResult.retryable(
                "stage3_analysis_internal_error",
                "Stage 3 analysis failed.",
            )

    async def _execute(self, context: JobHandlerContext) -> JobHandlerResult:
        analysis_id = str(context.job.payload.get("analysis_id") or "")
        stage2_job_id = str(context.job.payload.get("stage2_job_id") or "")
        revision = context.job.payload.get("analysis_revision")
        if (
            not analysis_id
            or analysis_id != context.job.entity_id
            or not stage2_job_id
            or not isinstance(revision, int)
        ):
            return JobHandlerResult.non_retryable(
                "stage3_analysis_job_invalid",
                "Stage 3 analysis job payload is invalid.",
            )

        with context.dependencies.session_factory() as session:
            row = session.scalar(
                select(RrugcStage3AnalysisModel).where(
                    RrugcStage3AnalysisModel.id == analysis_id,
                    RrugcStage3AnalysisModel.tenant_id == context.job.tenant_id,
                )
            )
            stage2 = session.scalar(
                select(RrugcStage2JobModel).where(
                    RrugcStage2JobModel.id == stage2_job_id,
                    RrugcStage2JobModel.tenant_id == context.job.tenant_id,
                )
            )
            if row is None or stage2 is None:
                return JobHandlerResult.non_retryable(
                    "stage3_analysis_not_found",
                    "Stage 3 analysis source was not found.",
                )
            if row.analysis_revision != revision:
                return JobHandlerResult.completed()
            if row.status in {"ready", "rejected"}:
                return JobHandlerResult.completed()
            if (
                stage2.status != "completed"
                or not stage2.output_remote_file_id
            ):
                return JobHandlerResult.non_retryable(
                    "stage3_stage2_output_not_ready",
                    "Stage 2 output is not ready for Stage 3 analysis.",
                )

            row.status = "analyzing"
            row.started_at = row.started_at or datetime.now(timezone.utc)
            row.last_error_code = None
            row.last_error_message = None
            session.commit()

            remote_file_id = stage2.output_remote_file_id
            content_type = stage2.output_content_type
            size_bytes = stage2.output_size_bytes

        storage = context.dependencies.storage_provider
        if storage is None:
            raise AnalysisImageError(
                "Managed storage is unavailable.",
                code="managed_storage_unavailable",
                retryable=True,
            )

        prepared = await AnalysisImagePreparer(storage).prepare(
            OpenStoredAssetInput(
                tenant_id=context.job.tenant_id,
                asset_id=f"rrugc-stage3:{analysis_id}",
                remote_file_id=remote_file_id,
                content_type=content_type,
                size_bytes=size_bytes,
            )
        )

        registry = context.dependencies.ai_provider_registry
        if registry is None:
            raise AiProviderUnavailableError("gemini")
        provider = registry.require("gemini")
        slot = scheduled_rrugc_gemini_slot(context.job)
        result = await provider.analyze_single(
            AiMetadataAnalysisInput(
                tenant_id=context.job.tenant_id,
                asset_id=stage2_job_id,
                prompt=stage3_analysis_prompt(),
                image_bytes=prepared.content,
                image_mime_type=prepared.mime_type,
                metadata_profile="rrugc_stage3_ugc_review",
                metadata_profile_version=STAGE3_ANALYSIS_VERSION,
                image_width=prepared.width,
                image_height=prepared.height,
                json_schema=Stage3UgcAnalysisDocument.model_json_schema(),
                analysis_id=analysis_id,
                preferred_model=(slot.model if slot else None),
                preferred_credential_provider=(
                    slot.credential_provider if slot else None
                ),
            )
        )
        document = Stage3UgcAnalysisDocument.model_validate(
            normalize_stage3_metadata(dict(result.metadata))
        )
        decision = evaluate_stage3(document)

        with context.dependencies.session_factory() as session:
            row = session.scalar(
                select(RrugcStage3AnalysisModel).where(
                    RrugcStage3AnalysisModel.id == analysis_id,
                    RrugcStage3AnalysisModel.tenant_id == context.job.tenant_id,
                )
            )
            if row is None or row.analysis_revision != revision:
                return JobHandlerResult.completed()
            row.status = decision.status
            row.people_count = document.people_count
            row.person_visible = document.person_visible
            row.hat_visible = document.hat_visible
            row.product_visible = document.product_visible
            row.embroidery_visible = document.embroidery_visible
            row.mobile_ugc_score = document.mobile_ugc_score
            row.photorealism_score = document.photorealism_score
            row.product_visibility_score = document.product_visibility_score
            row.review_fit_score = document.review_fit_score
            row.final_score = decision.final_score
            row.scene_type = document.scene_type
            row.framing_type = document.framing_type
            row.summary = document.summary
            row.reviewer_name = reviewer_name_for_analysis(analysis_id)
            row.star_rating = star_rating_for_analysis(analysis_id)
            row.review_text = review_text_for_analysis(document, analysis_id)
            row.review_generated_at = datetime.now(timezone.utc)
            row.evidence_json = list(document.evidence)
            row.reject_reasons_json = list(decision.reject_reasons)
            row.provider = result.provider
            row.model = result.model
            row.last_error_code = None
            row.last_error_message = None
            row.completed_at = datetime.now(timezone.utc)
            session.commit()

        context.logger.info(
            "rrugc_stage3_analysis_completed",
            extra={
                "analysis_id": analysis_id,
                "stage2_job_id": stage2_job_id,
                "tenant_id": context.job.tenant_id,
                "status": decision.status,
                "final_score": decision.final_score,
            },
        )
        return JobHandlerResult.completed()

    def _mark_error(
        self,
        context: JobHandlerContext,
        code: str,
        message: str,
    ) -> None:
        analysis_id = str(context.job.payload.get("analysis_id") or context.job.entity_id)
        try:
            with context.dependencies.session_factory() as session:
                row = session.scalar(
                    select(RrugcStage3AnalysisModel).where(
                        RrugcStage3AnalysisModel.id == analysis_id,
                        RrugcStage3AnalysisModel.tenant_id == context.job.tenant_id,
                    )
                )
                if row is None:
                    return
                row.status = "error"
                row.last_error_code = code[:100]
                row.last_error_message = message[:2000]
                session.commit()
        except Exception:
            context.logger.exception(
                "rrugc_stage3_analysis_error_state_failed",
                extra={"analysis_id": analysis_id},
            )
