import { describe, expect, it } from "vitest";
import { VIDEO_SEARCH_LIMIT, buildVideoSearchRequestBody, isCurrentVideoSearchResponse, mergeVideoSearchItems, parseVideoSearchResponse, videoSearchErrorMessage } from "./useVideoSearch";
describe("video search API contract", () => {
  it("uses ten videos per page without tenant identity", () => { const request = buildVideoSearchRequestBody(" horse riding ", 0, null, []); expect(VIDEO_SEARCH_LIMIT).toBe(10); expect(request).toEqual({ query: "horse riding", limit: 10, offset: 0 }); expect(request).not.toHaveProperty("tenant_id"); });
  it("uses the loaded item count as the next video offset", () => { expect(buildVideoSearchRequestBody("horse riding", 10, "source-a", ["petfull"])).toEqual({ query: "horse riding", limit: 10, offset: 10, external_source_id: "source-a", design_types: ["petfull"] }); });
  it("keeps the approved VIDEO-7A response fields", () => { const value = parseVideoSearchResponse({ items: [{ source_asset_id: "asset-a", analysis_run_id: "run-a", filename: "ride.mp4", mime_type: "video/mp4", duration_ms: 30000, source_type: "google_drive", external_source_id: "source-a", external_asset_id: "file-a", web_url: "https://drive.example/file-a", thumbnail_url: null, score: 10.5, best_match: { start_ms: 12000, end_ms: 18500, summary: "horse riding through field", visual_description: "rider on a horse", speech: "", confidence: 0.92, score: 6.1 }, matches: [] }], total: 1, took_ms: 3 }); expect(value.items[0].best_match.start_ms).toBe(12000); expect(value.total).toBe(1); });
  it("appends video pages without duplicates", () => { const first = parseVideoSearchResponse({ items: [{ source_asset_id: "asset-a", analysis_run_id: "run-a", filename: "a.mp4", mime_type: "video/mp4", duration_ms: null, source_type: null, external_source_id: null, external_asset_id: null, web_url: null, thumbnail_url: null, score: 1, best_match: { start_ms: 0, end_ms: 1, summary: "", visual_description: "", speech: "", confidence: 1, score: 1 }, matches: [] }], total: 2, took_ms: 1 }).items; expect(mergeVideoSearchItems(first, [...first])).toHaveLength(1); });
  it("does not accept stale responses and presents safe availability errors", () => { expect(isCurrentVideoSearchResponse(1, 2)).toBe(false); expect(isCurrentVideoSearchResponse(2, 2)).toBe(true); expect(videoSearchErrorMessage(503, { detail: { message: "http://internal-es" } })).toBe("Video search is temporarily unavailable. Please try again later."); });
});
