"""Add AI usage, budgets, cost rates and pilot runs.

Revision ID: 0011_ai_governance_pilot
Revises: 0010_tenant_processing_policies

Rollback: enable AI_EMERGENCY_STOP_ENABLED, drain AI workers, export usage and
pilot reports, then downgrade. Analysis and asset records are retained.
"""
from alembic import op
import sqlalchemy as sa
revision="0011_ai_governance_pilot"
down_revision="0010_tenant_processing_policies"
branch_labels=None
depends_on=None

def upgrade():
    op.create_table("ai_cost_rates",
        sa.Column("id",sa.String(36),primary_key=True),sa.Column("provider",sa.String(100),nullable=False),sa.Column("model",sa.String(255),nullable=False),sa.Column("effective_at",sa.DateTime(timezone=True),nullable=False),
        sa.Column("input_unit_cost",sa.Numeric(24,12),nullable=False),sa.Column("output_unit_cost",sa.Numeric(24,12),nullable=False),sa.Column("media_unit_cost",sa.Numeric(24,12),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),
        sa.UniqueConstraint("provider","model","effective_at",name="uq_ai_cost_rate_version"),sa.CheckConstraint("input_unit_cost >= 0 AND output_unit_cost >= 0 AND media_unit_cost >= 0",name="ck_ai_cost_rates_nonnegative"))
    op.create_index("ix_ai_cost_rates_resolve","ai_cost_rates",["provider","model","effective_at"])
    op.create_table("tenant_ai_budget_policies",
        sa.Column("tenant_id",sa.String(255),primary_key=True),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("daily_limit_micros",sa.BigInteger()),sa.Column("monthly_limit_micros",sa.BigInteger()),sa.Column("per_run_limit_micros",sa.BigInteger()),sa.Column("warning_threshold_percent",sa.Integer(),nullable=False,server_default="80"),sa.Column("hard_stop_threshold_percent",sa.Integer(),nullable=False,server_default="100"),sa.Column("timezone",sa.String(64),nullable=False,server_default="UTC"),sa.Column("currency",sa.String(3),nullable=False,server_default="USD"),sa.Column("action_on_limit",sa.String(20),nullable=False,server_default="defer"),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),
        sa.CheckConstraint("daily_limit_micros IS NULL OR daily_limit_micros >= 0",name="ck_ai_budget_daily"),sa.CheckConstraint("monthly_limit_micros IS NULL OR monthly_limit_micros >= 0",name="ck_ai_budget_monthly"),sa.CheckConstraint("per_run_limit_micros IS NULL OR per_run_limit_micros >= 0",name="ck_ai_budget_run"),sa.CheckConstraint("warning_threshold_percent >= 0 AND warning_threshold_percent <= 100",name="ck_ai_budget_warning"),sa.CheckConstraint("hard_stop_threshold_percent > 0 AND hard_stop_threshold_percent <= 100",name="ck_ai_budget_hard"),sa.CheckConstraint("warning_threshold_percent <= hard_stop_threshold_percent",name="ck_ai_budget_threshold_order"),sa.CheckConstraint("action_on_limit IN ('defer','reject')",name="ck_ai_budget_action"))
    op.create_table("ai_budget_accounts",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(255),nullable=False),sa.Column("period_type",sa.String(20),nullable=False),sa.Column("period_key",sa.String(64),nullable=False),sa.Column("currency",sa.String(3),nullable=False,server_default="USD"),sa.Column("limit_micros",sa.BigInteger(),nullable=False),sa.Column("reserved_micros",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("actual_micros",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","period_type","period_key","currency",name="uq_ai_budget_account_period"),sa.CheckConstraint("period_type IN ('daily','monthly','pilot')",name="ck_ai_budget_account_type"),sa.CheckConstraint("reserved_micros >= 0 AND actual_micros >= 0 AND limit_micros >= 0",name="ck_ai_budget_account_values"))
    op.create_index("ix_ai_budget_accounts_tenant_period","ai_budget_accounts",["tenant_id","period_type","period_key"])
    op.create_table("ai_budget_reservations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(255),nullable=False),sa.Column("operation_key",sa.String(512),nullable=False),sa.Column("analysis_id",sa.String(36)),sa.Column("job_id",sa.String(36)),sa.Column("pilot_run_id",sa.String(36)),sa.Column("estimated_cost_micros",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("actual_cost_micros",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("currency",sa.String(3),nullable=False,server_default="USD"),sa.Column("status",sa.String(20),nullable=False),sa.Column("account_keys_json",sa.JSON(),nullable=False),sa.Column("denial_code",sa.String(100)),sa.Column("denial_reason",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","operation_key",name="uq_ai_budget_reservation_operation"),sa.CheckConstraint("status IN ('reserved','reconciled','released','denied')",name="ck_ai_budget_reservation_status"),sa.CheckConstraint("estimated_cost_micros >= 0 AND actual_cost_micros >= 0",name="ck_ai_budget_reservation_cost"))
    op.create_index("ix_ai_budget_reservations_tenant_status","ai_budget_reservations",["tenant_id","status","created_at"])
    op.create_table("ai_usage_records",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(255),nullable=False),sa.Column("provider_operation_key",sa.String(512),nullable=False),sa.Column("asset_id",sa.String(36)),sa.Column("analysis_id",sa.String(36)),sa.Column("job_id",sa.String(36)),sa.Column("provider",sa.String(100),nullable=False),sa.Column("model",sa.String(255)),sa.Column("metadata_profile",sa.String(255)),sa.Column("metadata_profile_version",sa.String(100)),sa.Column("prompt_version",sa.String(100)),sa.Column("input_units",sa.Integer(),nullable=False,server_default="0"),sa.Column("output_units",sa.Integer(),nullable=False,server_default="0"),sa.Column("media_units",sa.Integer(),nullable=False,server_default="0"),sa.Column("provider_reported_cost_micros",sa.BigInteger()),sa.Column("locally_estimated_cost_micros",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("currency",sa.String(3),nullable=False),sa.Column("latency_ms",sa.Integer(),nullable=False,server_default="0"),sa.Column("outcome",sa.String(32),nullable=False),sa.Column("retry_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("provider_request_id",sa.String(255)),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tenant_id","provider_operation_key",name="uq_ai_usage_operation"),sa.CheckConstraint("outcome IN ('completed','provider_failed','invalid_metadata','budget_blocked','cancelled')",name="ck_ai_usage_outcome"))
    op.create_index("ix_ai_usage_tenant_occurred","ai_usage_records",["tenant_id","occurred_at"]); op.create_index("ix_ai_usage_analysis","ai_usage_records",["analysis_id"])
    op.create_table("ai_budget_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(255),nullable=False),sa.Column("actor_id",sa.String(255)),sa.Column("action",sa.String(64),nullable=False),sa.Column("reason",sa.Text()),sa.Column("details_json",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False)); op.create_index("ix_ai_budget_events_tenant_created","ai_budget_events",["tenant_id","created_at"])
    op.create_table("ai_pilot_runs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("tenant_id",sa.String(255),nullable=False),sa.Column("metadata_profile_id",sa.String(36),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("selection_json",sa.JSON(),nullable=False),sa.Column("sample_seed",sa.String(255),nullable=False),sa.Column("maximum_items",sa.Integer(),nullable=False),sa.Column("estimated_max_cost_micros",sa.BigInteger(),nullable=False,server_default="0"),sa.Column("currency",sa.String(3),nullable=False),sa.Column("cancellation_requested",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_by",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tenant_id","id",name="uq_ai_pilot_runs_tenant_id"),sa.CheckConstraint("status IN ('pending','running','completed','cancelled','failed')",name="ck_ai_pilot_status")); op.create_index("ix_ai_pilot_runs_tenant_status","ai_pilot_runs",["tenant_id","status","created_at"])
    op.create_table("ai_pilot_items",sa.Column("id",sa.String(36),primary_key=True),sa.Column("run_id",sa.String(36),nullable=False),sa.Column("tenant_id",sa.String(255),nullable=False),sa.Column("asset_id",sa.String(36),nullable=False),sa.Column("analysis_id",sa.String(36)),sa.Column("job_id",sa.String(36)),sa.Column("status",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["tenant_id","run_id"],["ai_pilot_runs.tenant_id","ai_pilot_runs.id"],ondelete="CASCADE",name="fk_ai_pilot_item_tenant_run"),sa.UniqueConstraint("run_id","asset_id",name="uq_ai_pilot_item_asset"),sa.CheckConstraint("status IN ('pending','enqueued','completed','failed','budget_blocked','cancelled')",name="ck_ai_pilot_item_status")); op.create_index("ix_ai_pilot_items_run_status","ai_pilot_items",["run_id","status"])
    with op.batch_alter_table("asset_ai_analyses") as batch:
        batch.drop_constraint("ck_asset_ai_analyses_status",type_="check")
        batch.create_check_constraint("ck_asset_ai_analyses_status","status IN ('pending','running','completed','failed','budget_blocked')")

def downgrade():
    with op.batch_alter_table("asset_ai_analyses") as batch:
        batch.drop_constraint("ck_asset_ai_analyses_status",type_="check")
        batch.create_check_constraint("ck_asset_ai_analyses_status","status IN ('pending','running','completed','failed')")
    for index,table in [("ix_ai_pilot_items_run_status","ai_pilot_items"),("ix_ai_pilot_runs_tenant_status","ai_pilot_runs"),("ix_ai_budget_events_tenant_created","ai_budget_events"),("ix_ai_usage_analysis","ai_usage_records"),("ix_ai_usage_tenant_occurred","ai_usage_records"),("ix_ai_budget_reservations_tenant_status","ai_budget_reservations"),("ix_ai_budget_accounts_tenant_period","ai_budget_accounts"),("ix_ai_cost_rates_resolve","ai_cost_rates")]: op.drop_index(index,table_name=table)
    for table in ["ai_pilot_items","ai_pilot_runs","ai_budget_events","ai_usage_records","ai_budget_reservations","ai_budget_accounts","tenant_ai_budget_policies","ai_cost_rates"]: op.drop_table(table)
