"""add inventory persistence models

Revision ID: a7dd7ccdbf1a
Revises: 0033_inventory_isolation
Create Date: 2026-08-09 20:14:26.732450
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a7dd7ccdbf1a'
down_revision: Union[str, None] = '0033_inventory_isolation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_daily_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('location_state_json', sa.JSON(), nullable=False),
    sa.Column('finalized_with_missing', sa.Boolean(), nullable=False),
    sa.Column('report_version', sa.Integer(), nullable=False),
    sa.Column('finalized_by', sa.String(length=255), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open','checking','ready','finalized','failed')", name='ck_inventory_daily_runs_status'),
    sa.CheckConstraint('report_version >= 0', name='ck_inventory_daily_runs_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'business_date', name='uq_inventory_daily_runs_tenant_date'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_daily_runs_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_inventory_daily_runs_tenant_key')
    )
    op.create_index('ix_inventory_daily_runs_status', 'inventory_daily_runs', ['tenant_id', 'status', 'business_date'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('base_unit', sa.String(length=64), nullable=False),
    sa.Column('whole_unit', sa.String(length=64), nullable=True),
    sa.Column('fraction_unit', sa.String(length=64), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('conversion_factor > 0', name='ck_inventory_items_conversion'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_items_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_inventory_items_tenant_sku')
    )
    op.create_index('ix_inventory_items_tenant_active', 'inventory_items', ['tenant_id', 'active'], unique=False)
    op.create_table('inventory_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_inventory_locations_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_locations_tenant_id')
    )
    op.create_index('ix_inventory_locations_tenant_active', 'inventory_locations', ['tenant_id', 'active'], unique=False)
    op.create_table('inventory_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('external_source_id', sa.String(length=36), nullable=False),
    sa.Column('inbox_folder_id', sa.String(length=2048), nullable=False),
    sa.Column('processed_folder_id', sa.String(length=2048), nullable=True),
    sa.Column('reupload_folder_id', sa.String(length=2048), nullable=True),
    sa.Column('excel_folder_id', sa.String(length=2048), nullable=True),
    sa.Column('backup_folder_id', sa.String(length=2048), nullable=True),
    sa.Column('excel_template_file_id', sa.String(length=2048), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('auto_approve_confidence', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('review_confidence', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('drive_poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('archive_enabled', sa.Boolean(), nullable=False),
    sa.Column('excel_export_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('auto_approve_confidence >= 0 AND auto_approve_confidence <= 1', name='ck_inventory_settings_auto_confidence'),
    sa.CheckConstraint('drive_poll_interval_seconds > 0', name='ck_inventory_settings_poll_interval'),
    sa.CheckConstraint('review_confidence <= auto_approve_confidence', name='ck_inventory_settings_confidence_order'),
    sa.CheckConstraint('review_confidence >= 0 AND review_confidence <= 1', name='ck_inventory_settings_review_confidence'),
    sa.ForeignKeyConstraint(['tenant_id', 'external_source_id'], ['external_sources.tenant_id', 'external_sources.id'], name='fk_inventory_settings_tenant_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_inventory_settings_tenant')
    )
    op.create_table('inventory_source_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('external_source_id', sa.String(length=36), nullable=False),
    sa.Column('drive_file_id', sa.String(length=2048), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('drive_modified_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('drive_size', sa.BigInteger(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider_metadata_json', sa.JSON(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('discovered','downloaded','processing','processed','ignored','failed')", name='ck_inventory_source_files_status'),
    sa.CheckConstraint('drive_size IS NULL OR drive_size >= 0', name='ck_inventory_source_files_size'),
    sa.ForeignKeyConstraint(['tenant_id', 'external_source_id'], ['external_sources.tenant_id', 'external_sources.id'], name='fk_inventory_source_files_tenant_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_source_id', 'drive_file_id', 'drive_modified_time', name='uq_inventory_source_files_provider_version'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_source_files_tenant_id')
    )
    op.create_index('ix_inventory_source_files_content_hash', 'inventory_source_files', ['tenant_id', 'content_sha256'], unique=False)
    op.create_index('ix_inventory_source_files_drive_identity', 'inventory_source_files', ['tenant_id', 'external_source_id', 'drive_file_id'], unique=False)
    op.create_index('ix_inventory_source_files_tenant_status', 'inventory_source_files', ['tenant_id', 'status', 'updated_at'], unique=False)
    op.create_table('inventory_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('expected_pages', sa.Integer(), nullable=False),
    sa.Column('received_pages', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("document_type IN ('stock_count','warehouse_transfer','waste')", name='ck_inventory_documents_type'),
    sa.CheckConstraint("status IN ('collecting','analyzing','needs_review','approved','rejected','finalized')", name='ck_inventory_documents_status'),
    sa.CheckConstraint('expected_pages >= 0', name='ck_inventory_documents_expected_pages'),
    sa.CheckConstraint('received_pages >= 0', name='ck_inventory_documents_received_pages'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id'], ['inventory_locations.tenant_id', 'inventory_locations.id'], name='fk_inventory_documents_tenant_location', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_documents_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_inventory_documents_tenant_key')
    )
    op.create_index('ix_inventory_documents_tenant_date', 'inventory_documents', ['tenant_id', 'business_date', 'status'], unique=False)
    op.create_index('ix_inventory_documents_tenant_location', 'inventory_documents', ['tenant_id', 'location_id', 'business_date'], unique=False)
    op.create_table('inventory_exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('daily_run_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('export_version', sa.Integer(), nullable=False),
    sa.Column('export_format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('drive_file_id', sa.String(length=2048), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("export_format IN ('xlsx','xlsm','csv')", name='ck_inventory_exports_format'),
    sa.CheckConstraint("status IN ('pending','generating','completed','failed')", name='ck_inventory_exports_status'),
    sa.CheckConstraint('export_version > 0', name='ck_inventory_exports_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'daily_run_id'], ['inventory_daily_runs.tenant_id', 'inventory_daily_runs.id'], name='fk_inventory_exports_tenant_daily_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'daily_run_id', 'export_version', 'export_format', name='uq_inventory_exports_run_version'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_exports_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_inventory_exports_tenant_key')
    )
    op.create_index('ix_inventory_exports_run', 'inventory_exports', ['tenant_id', 'daily_run_id', 'created_at'], unique=False)
    op.create_index('ix_inventory_exports_status', 'inventory_exports', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_table('inventory_item_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('normalized_alias', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'item_id'], ['inventory_items.tenant_id', 'inventory_items.id'], name='fk_inventory_aliases_tenant_item', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_aliases_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'normalized_alias', name='uq_inventory_aliases_tenant_normalized')
    )
    op.create_index('ix_inventory_aliases_tenant_item', 'inventory_item_aliases', ['tenant_id', 'item_id'], unique=False)
    op.create_table('inventory_document_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('drive_file_id', sa.String(length=2048), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('duplicate_of_page_id', sa.String(length=36), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("analysis_status IN ('pending','processing','completed','failed','skipped')", name='ck_inventory_pages_analysis_status'),
    sa.CheckConstraint('page_count > 0', name='ck_inventory_pages_count'),
    sa.CheckConstraint('page_number > 0', name='ck_inventory_pages_number'),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['inventory_documents.tenant_id', 'inventory_documents.id'], name='fk_inventory_pages_tenant_document', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'duplicate_of_page_id'], ['inventory_document_pages.tenant_id', 'inventory_document_pages.id'], name='fk_inventory_pages_tenant_duplicate', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'source_file_id'], ['inventory_source_files.tenant_id', 'inventory_source_files.id'], name='fk_inventory_pages_tenant_source_file', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'document_id', 'page_number', name='uq_inventory_pages_document_number'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_pages_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'source_file_id', name='uq_inventory_pages_tenant_source_file')
    )
    op.create_index('ix_inventory_pages_content_hash', 'inventory_document_pages', ['tenant_id', 'content_sha256'], unique=False)
    op.create_index('ix_inventory_pages_document', 'inventory_document_pages', ['tenant_id', 'document_id', 'page_number'], unique=False)
    op.create_table('inventory_ai_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('raw_result_json', sa.JSON(), nullable=False),
    sa.Column('normalized_result_json', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','processing','completed','failed','superseded')", name='ck_inventory_ai_status'),
    sa.CheckConstraint("validation_status IN ('unvalidated','valid','invalid','needs_review')", name='ck_inventory_ai_validation'),
    sa.CheckConstraint('analysis_version > 0', name='ck_inventory_ai_version'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_inventory_ai_confidence'),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['inventory_documents.tenant_id', 'inventory_documents.id'], name='fk_inventory_ai_tenant_document', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'page_id'], ['inventory_document_pages.tenant_id', 'inventory_document_pages.id'], name='fk_inventory_ai_tenant_page', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_ai_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_inventory_ai_tenant_key'),
    sa.UniqueConstraint('tenant_id', 'page_id', 'analysis_version', name='uq_inventory_ai_page_version')
    )
    op.create_index('ix_inventory_ai_document', 'inventory_ai_analyses', ['tenant_id', 'document_id', 'created_at'], unique=False)
    op.create_index('ix_inventory_ai_page_status', 'inventory_ai_analyses', ['tenant_id', 'page_id', 'status'], unique=False)
    op.create_table('inventory_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('raw_item_name', sa.String(length=1024), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('raw_values_json', sa.JSON(), nullable=False),
    sa.Column('normalized_values_json', sa.JSON(), nullable=False),
    sa.Column('whole_quantity', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('fraction_quantity', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('whole_unit', sa.String(length=64), nullable=True),
    sa.Column('fraction_unit', sa.String(length=64), nullable=True),
    sa.Column('conversion_factor_snapshot', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('quantity_base_unit', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('waste_quantity', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('waste_reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("validation_status IN ('unvalidated','valid','invalid','needs_review','corrected')", name='ck_inventory_lines_validation'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_inventory_lines_confidence'),
    sa.CheckConstraint('line_number > 0', name='ck_inventory_lines_number'),
    sa.ForeignKeyConstraint(['tenant_id', 'analysis_id'], ['inventory_ai_analyses.tenant_id', 'inventory_ai_analyses.id'], name='fk_inventory_lines_tenant_analysis', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['inventory_documents.tenant_id', 'inventory_documents.id'], name='fk_inventory_lines_tenant_document', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'item_id'], ['inventory_items.tenant_id', 'inventory_items.id'], name='fk_inventory_lines_tenant_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'page_id'], ['inventory_document_pages.tenant_id', 'inventory_document_pages.id'], name='fk_inventory_lines_tenant_page', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'analysis_id', 'line_number', name='uq_inventory_lines_analysis_number'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_lines_tenant_id')
    )
    op.create_index('ix_inventory_lines_document', 'inventory_lines', ['tenant_id', 'document_id', 'line_number'], unique=False)
    op.create_index('ix_inventory_lines_item', 'inventory_lines', ['tenant_id', 'item_id', 'created_at'], unique=False)
    op.create_table('inventory_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('line_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('original_value_json', sa.JSON(), nullable=False),
    sa.Column('suggested_value_json', sa.JSON(), nullable=False),
    sa.Column('final_value_json', sa.JSON(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','in_review','approved','rejected','cancelled')", name='ck_inventory_reviews_status'),
    sa.ForeignKeyConstraint(['tenant_id', 'document_id'], ['inventory_documents.tenant_id', 'inventory_documents.id'], name='fk_inventory_reviews_tenant_document', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'line_id'], ['inventory_lines.tenant_id', 'inventory_lines.id'], name='fk_inventory_reviews_tenant_line', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_reviews_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_inventory_reviews_tenant_key')
    )
    op.create_index('ix_inventory_reviews_document', 'inventory_reviews', ['tenant_id', 'document_id'], unique=False)
    op.create_index('ix_inventory_reviews_queue', 'inventory_reviews', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('quantity_base_unit', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('base_unit_snapshot', sa.String(length=64), nullable=False),
    sa.Column('conversion_factor_snapshot', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('source_line_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reverses_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('posted','reversed')", name='ck_inventory_transactions_status'),
    sa.CheckConstraint("transaction_type IN ('opening_balance','receipt','transfer_out','transfer_in','closing_count','waste','usage_adjustment')", name='ck_inventory_transactions_type'),
    sa.CheckConstraint('conversion_factor_snapshot > 0', name='ck_inventory_transactions_conversion'),
    sa.ForeignKeyConstraint(['tenant_id', 'item_id'], ['inventory_items.tenant_id', 'inventory_items.id'], name='fk_inventory_transactions_tenant_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id'], ['inventory_locations.tenant_id', 'inventory_locations.id'], name='fk_inventory_transactions_tenant_location', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'reverses_transaction_id'], ['inventory_transactions.tenant_id', 'inventory_transactions.id'], name='fk_inventory_transactions_tenant_reversal', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'source_document_id'], ['inventory_documents.tenant_id', 'inventory_documents.id'], name='fk_inventory_transactions_tenant_document', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'source_line_id'], ['inventory_lines.tenant_id', 'inventory_lines.id'], name='fk_inventory_transactions_tenant_line', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_inventory_transactions_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_inventory_transactions_tenant_key')
    )
    op.create_index('ix_inventory_transactions_document', 'inventory_transactions', ['tenant_id', 'source_document_id'], unique=False)
    op.create_index('ix_inventory_transactions_ledger', 'inventory_transactions', ['tenant_id', 'business_date', 'location_id', 'item_id', 'created_at'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_transactions')
    op.drop_index('ix_inventory_reviews_queue', table_name='inventory_reviews')
    op.drop_index('ix_inventory_reviews_document', table_name='inventory_reviews')
    op.drop_table('inventory_reviews')
    op.drop_index('ix_inventory_lines_item', table_name='inventory_lines')
    op.drop_index('ix_inventory_lines_document', table_name='inventory_lines')
    op.drop_table('inventory_lines')
    op.drop_index('ix_inventory_ai_page_status', table_name='inventory_ai_analyses')
    op.drop_index('ix_inventory_ai_document', table_name='inventory_ai_analyses')
    op.drop_table('inventory_ai_analyses')
    op.drop_index('ix_inventory_pages_document', table_name='inventory_document_pages')
    op.drop_index('ix_inventory_pages_content_hash', table_name='inventory_document_pages')
    op.drop_table('inventory_document_pages')
    op.drop_index('ix_inventory_aliases_tenant_item', table_name='inventory_item_aliases')
    op.drop_table('inventory_item_aliases')
    op.drop_index('ix_inventory_exports_status', table_name='inventory_exports')
    op.drop_index('ix_inventory_exports_run', table_name='inventory_exports')
    op.drop_table('inventory_exports')
    op.drop_index('ix_inventory_documents_tenant_location', table_name='inventory_documents')
    op.drop_index('ix_inventory_documents_tenant_date', table_name='inventory_documents')
    op.drop_table('inventory_documents')
    op.drop_index('ix_inventory_source_files_tenant_status', table_name='inventory_source_files')
    op.drop_index('ix_inventory_source_files_drive_identity', table_name='inventory_source_files')
    op.drop_index('ix_inventory_source_files_content_hash', table_name='inventory_source_files')
    op.drop_table('inventory_source_files')
    op.drop_table('inventory_settings')
    op.drop_index('ix_inventory_locations_tenant_active', table_name='inventory_locations')
    op.drop_table('inventory_locations')
    op.drop_index('ix_inventory_items_tenant_active', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('ix_inventory_daily_runs_status', table_name='inventory_daily_runs')
    op.drop_table('inventory_daily_runs')
    # ### end Alembic commands ###
