import type { ReferenceAsset, VideoGeneration, VideoGenerationCapabilities, VideoGenerationRequest } from "./types";
import { VideoGenerationApiError } from "./types";
type Fetcher = typeof fetch;
async function request<T>(path: string, init: RequestInit = {}, fetcher: Fetcher = fetch): Promise<T> { const response = await fetcher(path, { ...init, credentials: "same-origin", headers: { Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...init.headers } }); const body = await response.json().catch(() => ({})) as { detail?: string | { code?: string; message?: string } }; if (!response.ok) { const detail = body.detail; throw new VideoGenerationApiError(typeof detail === "string" ? detail : detail?.message || "Request failed (" + response.status + ")", response.status, typeof detail === "object" && detail?.code ? detail.code : response.status === 401 ? "authentication_required" : "request_failed"); } return body as T; }
export const fetchCapabilities = (signal?: AbortSignal, fetcher?: Fetcher) => request<VideoGenerationCapabilities>("/api/v1/video-generations/capabilities", { signal }, fetcher);
export const createGeneration = (body: VideoGenerationRequest, signal?: AbortSignal, fetcher?: Fetcher) => request<VideoGeneration>("/api/v1/video-generations", { method: "POST", body: JSON.stringify(body), signal }, fetcher);
export const fetchGeneration = (id: string, signal?: AbortSignal, fetcher?: Fetcher) => request<VideoGeneration>("/api/v1/video-generations/" + encodeURIComponent(id), { signal }, fetcher);
export const cancelGeneration = (id: string, signal?: AbortSignal, fetcher?: Fetcher) => request<VideoGeneration>("/api/v1/video-generations/" + encodeURIComponent(id) + "/cancel", { method: "POST", signal }, fetcher);
export const videoResultUrl = (id: string) => "/api/v1/video-generations/" + encodeURIComponent(id) + "/video";
export async function fetchReferenceAssets(signal?: AbortSignal, fetcher: Fetcher = fetch): Promise<ReferenceAsset[]> { const response = await fetcher("/api/explorer/children?parent_id=root&provider=google-drive&page_size=100", { signal, credentials: "same-origin", headers: { Accept: "application/json" } }); const body = await response.json().catch(() => ({})) as { children?: ReferenceAsset[] }; if (!response.ok) throw new VideoGenerationApiError("Unable to load CAM image assets.", response.status, "reference_assets_unavailable"); return (body.children || []).filter(asset => Boolean(asset.internal_asset_id)); }
