import { useEffect, useState } from "react";
import { fetchReferenceAssets } from "./api";
import type { ReferenceAsset, VideoGenerationCapabilities } from "./types";
type Props = { capabilities: VideoGenerationCapabilities; selected: ReferenceAsset[]; onChange: (assets: ReferenceAsset[]) => void; tenantKey: string; };
export function ReferenceAssetPicker({ capabilities, selected, onChange, tenantKey }: Props) {
  const [assets, setAssets] = useState<ReferenceAsset[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); setAssets([]); void fetchReferenceAssets(controller.signal).then(setAssets).catch(reason => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Unable to load CAM image assets."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [tenantKey]);
  const allowed = new Set(capabilities.allowed_reference_mime_types.map(value => value.toLowerCase())); const candidates = assets.filter(asset => allowed.has(asset.mime_type.split(";", 1)[0].toLowerCase())); const selectedIds = new Set(selected.map(asset => asset.internal_asset_id || asset.id)); const atMaximum = selected.length >= capabilities.max_references;
  function toggle(asset: ReferenceAsset) { const key = asset.internal_asset_id || asset.id; if (selectedIds.has(key)) onChange(selected.filter(item => (item.internal_asset_id || item.id) !== key)); else if (!atMaximum) onChange([...selected, asset]); }
  function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= selected.length) return; const next = [...selected]; [next[index], next[target]] = [next[target], next[index]]; onChange(next); }
  return <fieldset className="video-generation-references"><legend>Reference images <span>{selected.length} / {capabilities.max_references}</span></legend><p>Optional. Choose existing CAM JPEG, PNG or WEBP assets. Their displayed order is sent to the generation provider.</p>{loading && <p role="status">Loading available image assets...</p>}{error && <p className="video-generation-error" role="alert">{error}</p>}{!loading && !error && <div className="video-reference-grid" role="list" aria-label="CAM image assets">{candidates.length === 0 && <p className="video-generation-muted">No compatible CAM image assets are available in the current source.</p>}{candidates.map(asset => { const key = asset.internal_asset_id || asset.id; const position = selected.findIndex(item => (item.internal_asset_id || item.id) === key); const chosen = position >= 0; return <button key={key} type="button" role="listitem" className={"video-reference-asset " + (chosen ? "selected" : "")} disabled={!chosen && atMaximum} onClick={() => toggle(asset)} aria-pressed={chosen}>{asset.thumbnail_url ? <img src={asset.thumbnail_url} alt="" /> : <span className="video-reference-placeholder" aria-hidden="true">IMG</span>}<span title={asset.name}>{asset.name}</span>{chosen && <b aria-label={"Reference " + (position + 1)}>{position + 1}</b>}</button>; })}</div>}{selected.length > 0 && <ol className="video-reference-order" aria-label="Selected reference order">{selected.map((asset, index) => <li key={asset.internal_asset_id || asset.id}><span><b>{index + 1}</b>{asset.name}</span><span className="video-reference-order-actions"><button type="button" onClick={() => move(index, -1)} disabled={index === 0} aria-label={"Move " + asset.name + " up"}>Move up</button><button type="button" onClick={() => move(index, 1)} disabled={index === selected.length - 1} aria-label={"Move " + asset.name + " down"}>Move down</button><button type="button" onClick={() => toggle(asset)} aria-label={"Remove " + asset.name}>Remove</button></span></li>)}</ol>}</fieldset>;
}
